"""create papers table

Revision ID: 90f158397d95
Revises: ac0450700e55
Create Date: 2025-11-02 22:24:18.008466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f158397d95'
down_revision: Union[str, None] = 'ac0450700e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_papers_id', table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('authors', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='papers_pkey')
    )
    op.create_index('ix_papers_id', 'papers', ['id'], unique=False)
    # ### end Alembic commands ###
