"""add thumbnail column

Revision ID: eb16a9e98b49
Revises: fb7ccadd9cbb
Create Date: 2025-11-05 12:10:41.947273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb16a9e98b49'
down_revision: Union[str, None] = 'fb7ccadd9cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'thumbnail')
    # ### end Alembic commands ###
